/**:
  ros__parameters:
    camera_matrix: [1378.8670120451607, 0.0, 937.0810895286735,
                    0.0, 1379.0715949839703, 561.5996329656532,
                    0.0, 0.0, 1.0]
    dist_coeff: [-0.44422210350101066, 0.2541470051820158,
                0.0014616601794162248, -0.0006275944293412642,
                -0.0850860601858966]
    arena_marker_xy: [0.08, 0.08]
    # topics
    robots_pose_topic: "/robots/pose" # followed by /robot_id
    robots_intern_pose_topic: "/robots/intern_pose" # followed by /robot_id
    arena_pose_topic: "/arena/pose" # not used
    camera_topic: "/camera/raw"
    undistorted_camera_topic: "/camera/undistorted"

cam2topic:
  ros__parameters:
    camera_index: 4 # v4l2-ctl --list-devices (sudo apt install v4l-utils)
    image_width: 1920
    image_height: 1080

pose_estimator:
  ros__parameters:
    ArUcoDictionary: 0 # DICT_4X4_50
    ArenaArUcoMarkerSize: 0.08
    MechalinoArUcoMarkerSize: 0.066
    arena_ArUcoID: 0
    cutoff_freq: 1.0
odom_publisher:
  ros__parameters:
    odom_publisher_frequency: 2.0
    ip_list_file: "/opt/mechalinos/ip_list.txt"
    http_timeout: 0.5