/**:
  ros__parameters:
    camera_matrix: [1334.6869496371785, 0.0, 914.9379678018371,
                    0.0, 1334.4909345531835, 560.9988948543311,
                    0.0, 0.0, 1.0]
    dist_coeff: [-0.440399702197229, 0.26768213854994716,
                0.0028466070165869247, 0.0016047037230352734,
                -0.09913753835216463]
    arena_marker_xy: [0.08, 0.08]
    # topics
    robots_pose_topic: "/robots/pose" # followed by /robot_id
    robots_intern_pose_topic: "/robots/intern_pose" # followed by /robot_id
    arena_pose_topic: "/arena/pose" # not used
    camera_topic: "/camera/raw"
    undistorted_camera_topic: "/camera/undistorted"

cam2topic:
  ros__parameters:
    camera_index: 4
    image_width: 1920
    image_height: 1080

pose_estimator:
  ros__parameters:
    ArUcoDictionary: 0 # DICT_4X4_50
    ArenaArUcoMarkerSize: 0.08
    MechalinoArUcoMarkerSize: 0.066
    arena_ArUcoID: 0

odom_publisher:

  ros__parameters:
    odom_publisher_frequency: 1.0
    ip_list_file: "/opt/mechalinos/ip_list.txt"
    http_timeout: 0.5